## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
   obj = bld.create_ns3_program('openflow-switch',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'openflow-switch.cc'

   obj = bld.create_ns3_program('twoswitch-topology',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'twoswitch-topology.cc'

   obj = bld.create_ns3_program('single-controller-issue',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'single-controller-issue.cc'

   obj = bld.create_ns3_program('simpleloop-topology',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'simpleloop-topology.cc'

   obj = bld.create_ns3_program('sevenRing-topology',
                                ['openflow', 'csma', 'internet', 'applications'])
   obj.source = 'sevenRing-topology.cc'
